<#
.SYNOPSIS
    Mint a local-only developer API key from the seeded dev@example.com user.

.DESCRIPTION
    Queries the local Docker Postgres instance for the seeded dev user ID,
    then exchanges it for an API key via POST /v1/auth/exchange.

    The key is generated by the local API and returned ONLY to the calling
    process. It is LOCAL DEVELOPMENT ONLY and must never be used against
    production or staging endpoints.

    SECURITY RULES:
    - By default, the raw key is NOT printed to stdout.
    - Pass -PrintKey to print it (use only for scripted capture, not display).
    - The key is never written to disk unless -OutFile is specified.
    - The key is never included in reports, event payloads, or debug panels.
    - This script refuses to run if DATABASE_URL points to a non-local host.

.PARAMETER Help
    Show usage information and exit.

.PARAMETER PrintKey
    Print ONLY the raw API key to stdout (for capture by a parent process).
    Do not use this for interactive display - pipe it to a variable instead.

.PARAMETER Json
    Print a JSON object with { "keyMinted": true, "apiUrl": "..." }.
    The raw key is never included in JSON output.

.PARAMETER Quiet
    Suppress all non-error output (useful when -PrintKey is set).

.PARAMETER ApiUrl
    Local API base URL. Defaults to http://127.0.0.1:3001.

.PARAMETER DeviceId
    Device ID to use when minting the key. Defaults to local-real-api-smoke-device.

.PARAMETER OutFile
    Write the key to this file path (gitignored path required).
    If omitted, the key is held in memory only and returned via -PrintKey.

.EXAMPLE
    # Capture the key in a variable (safe - key never displayed)
    $key = .\scripts\get-local-dev-api-key.ps1 -PrintKey -Quiet
    $env:PROMPTPROFIT_DEV_API_KEY = $key

.EXAMPLE
    # Show JSON status (key not included)
    .\scripts\get-local-dev-api-key.ps1 -Json

.EXAMPLE
    # Show help
    pnpm -w run local:dev-api-key -- -Help

.NOTES
    Prerequisites:
      - Docker daemon running with postgres container active
      - pnpm db:seed applied (creates dev@example.com)
      - Local API running at http://127.0.0.1:3001
    This script uses "docker compose exec postgres psql" - no local psql required.
    DO NOT use the minted key against production or staging.
#>
[CmdletBinding()]
param(
    [switch]$Help,
    [switch]$PrintKey,
    [switch]$Json,
    [switch]$Quiet,
    [string]$ApiUrl   = "http://127.0.0.1:3001",
    [string]$DeviceId = "local-real-api-smoke-device",
    [string]$OutFile  = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Continue"

function Write-Log([string]$msg) {
    if (-not $Quiet) { Write-Host ("[--] " + $msg) -ForegroundColor Cyan }
}
function Write-Ok([string]$msg) {
    if (-not $Quiet) { Write-Host ("[OK] " + $msg) -ForegroundColor Green }
}
function Write-Err([string]$msg) { Write-Host ("[XX] " + $msg) -ForegroundColor Red }
function Write-Warn([string]$msg) {
    if (-not $Quiet) { Write-Host ("[!!] " + $msg) -ForegroundColor Yellow }
}

# ---------------------------------------------------------------------------
# Help mode
# ---------------------------------------------------------------------------

if ($Help) {
    Write-Host ""
    Write-Host "SYNOPSIS" -ForegroundColor Cyan
    Write-Host "  Mint a local-only developer API key from the seeded dev@example.com user."
    Write-Host ""
    Write-Host "USAGE"
    Write-Host "  .\scripts\get-local-dev-api-key.ps1 [-PrintKey] [-Json] [-Quiet]"
    Write-Host "                                       [-ApiUrl <url>] [-DeviceId <id>]"
    Write-Host "  pnpm -w run local:dev-api-key"
    Write-Host "  pnpm -w run local:dev-api-key -- -Help"
    Write-Host ""
    Write-Host "OPTIONS"
    Write-Host "  -Help         Show this help and exit."
    Write-Host "  -PrintKey     Print the raw key to stdout (for scripted capture)."
    Write-Host "  -Json         Print JSON status { keyMinted, apiUrl } (no key value)."
    Write-Host "  -Quiet        Suppress all non-error output."
    Write-Host "  -ApiUrl       Local API URL (default: http://127.0.0.1:3001)."
    Write-Host "  -DeviceId     Device ID for the exchange (default: local-real-api-smoke-device)."
    Write-Host "  -OutFile      Write key to a file (use a gitignored path like .tmp/)."
    Write-Host ""
    Write-Host "SECURITY"
    Write-Host "  The raw key is LOCAL DEVELOPMENT ONLY."
    Write-Host "  It is never printed by default, never logged, never in reports."
    Write-Host "  Use -PrintKey only in scripted (non-interactive) contexts."
    Write-Host ""
    Write-Host "EXAMPLE (safe capture)"
    Write-Host '  $key = .\scripts\get-local-dev-api-key.ps1 -PrintKey -Quiet'
    Write-Host '  $env:PROMPTPROFIT_DEV_API_KEY = $key'
    Write-Host ""
    exit 0
}

# ---------------------------------------------------------------------------
# Safety: validate that the API URL is local-only
# ---------------------------------------------------------------------------

$allowedHosts = @("localhost", "127.0.0.1", "::1")
$uriObj = $null
try {
    $uriObj = [System.Uri]$ApiUrl
} catch {
    Write-Err ("Invalid API URL: " + $ApiUrl)
    exit 3
}

$apiHost = $uriObj.Host
$isLocalHost = $false
foreach ($h in $allowedHosts) {
    if ($apiHost -eq $h) { $isLocalHost = $true; break }
}

if (-not $isLocalHost) {
    Write-Err "UNSAFE: API URL does not point to a local host."
    Write-Err ("  Provided: " + $ApiUrl)
    Write-Err "  This script only mints keys against localhost/127.0.0.1."
    Write-Err "  Never use this against production or staging endpoints."
    exit 3
}

Write-Log ("API target: " + $ApiUrl + " (local - safe)")

# ---------------------------------------------------------------------------
# Step 1: Query dev user ID from Docker Postgres
# ---------------------------------------------------------------------------

Write-Log "Querying dev user ID from local Docker Postgres..."

$psqlQuery = "SELECT id FROM users WHERE email = 'dev@example.com' LIMIT 1;"
$psqlArgs  = @(
    "compose", "exec", "-T", "postgres",
    "psql", "-U", "promptprofit", "-d", "promptprofit_dev",
    "-t", "-c", $psqlQuery
)

$psqlOutput = & docker @psqlArgs 2>&1
$psqlExit   = $LASTEXITCODE

if ($psqlExit -ne 0) {
    Write-Err "docker compose exec postgres psql failed (exit " + $psqlExit + ")."
    Write-Err "Is Docker running and is the postgres container healthy?"
    Write-Err "Run: docker compose up -d postgres"
    exit 2
}

# Trim whitespace from psql -t output
$userId = ($psqlOutput | Out-String).Trim()

if ($userId -eq "" -or $userId -like "*0 rows*") {
    Write-Err "No user found with email dev@example.com in local Postgres."
    Write-Err "Run: pnpm db:seed"
    exit 2
}

# Validate UUID format (basic check)
if ($userId -notmatch '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$') {
    Write-Err ("Unexpected user ID format from Postgres: '" + $userId + "'")
    Write-Err "Expected a UUID. Check that pnpm db:seed has been run."
    exit 2
}

Write-Ok "Found dev user (ID: [redacted - UUID verified])"

# ---------------------------------------------------------------------------
# Step 2: Mint API key via POST /v1/auth/exchange
# ---------------------------------------------------------------------------

Write-Log ("Minting local dev API key via " + $ApiUrl + "/v1/auth/exchange ...")

$exchangeBody = '{"deviceId":"' + $DeviceId + '","userId":"' + $userId + '"}'
$exchangeUri  = $ApiUrl + "/v1/auth/exchange"

$response = $null
try {
    $response = Invoke-WebRequest `
        -Uri $exchangeUri `
        -Method POST `
        -Body $exchangeBody `
        -ContentType "application/json" `
        -UseBasicParsing `
        -TimeoutSec 10 `
        -ErrorAction Stop
} catch {
    Write-Err ("POST /v1/auth/exchange failed: " + $_.Exception.Message)
    Write-Err ("Is the local API running at " + $ApiUrl + "?")
    Write-Err "Run: pnpm dev:api"
    exit 2
}

if ($response.StatusCode -ne 200 -and $response.StatusCode -ne 201) {
    Write-Err ("Unexpected HTTP " + $response.StatusCode + " from /v1/auth/exchange")
    exit 1
}

# Parse response JSON to extract data.apiKey
$responseObj = $null
try {
    $responseObj = $response.Content | ConvertFrom-Json
} catch {
    Write-Err "Failed to parse JSON response from /v1/auth/exchange."
    exit 1
}

# Support both { data: { apiKey } } and { apiKey } response shapes
$rawKey = $null
if ($responseObj.data -and $responseObj.data.apiKey) {
    $rawKey = $responseObj.data.apiKey
} elseif ($responseObj.apiKey) {
    $rawKey = $responseObj.apiKey
}

if (-not $rawKey -or $rawKey.Length -lt 20) {
    Write-Err "Could not extract a valid apiKey from /v1/auth/exchange response."
    Write-Err "(Key is shown exactly once - if the seed ran twice, re-seed or query existing key)"
    exit 1
}

if (-not $rawKey.StartsWith("ppft_")) {
    Write-Err "API key does not match expected format (must start with 'ppft_')."
    Write-Err "Check the /v1/auth/exchange response shape and the seed script."
    exit 1
}

Write-Ok "API key minted successfully (LOCAL DEVELOPMENT ONLY)."
Write-Warn "This key is local-only. Never use it against production or staging."

# ---------------------------------------------------------------------------
# Optional: write to gitignored file
# ---------------------------------------------------------------------------

if ($OutFile -ne "") {
    $outDir = Split-Path -Parent $OutFile
    if ($outDir -and -not (Test-Path $outDir)) {
        New-Item -ItemType Directory -Path $outDir -Force | Out-Null
    }
    try {
        Set-Content -Path $OutFile -Value $rawKey -NoNewline
        Write-Ok ("Key written to: " + $OutFile + " (gitignored)")
    } catch {
        Write-Err ("Failed to write key to " + $OutFile + ": " + $_.Exception.Message)
    }
}

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

if ($Json) {
    $jsonOut = '{"keyMinted":true,"apiUrl":"' + $ApiUrl + '","deviceId":"' + $DeviceId + '"}'
    Write-Host $jsonOut
}

if ($PrintKey) {
    # Write-Output sends to the Success pipeline so the parent can capture it.
    # Write-Host goes to the console Information stream and cannot be captured.
    Write-Output $rawKey
}

if (-not $PrintKey -and -not $Json) {
    Write-Log "Key minted. Use -PrintKey to capture it in a variable."
    Write-Log "Example: " + '$key = .\scripts\get-local-dev-api-key.ps1 -PrintKey -Quiet'
}

exit 0
