<#
.SYNOPSIS
    Opens the latest live ChatGPT smoke report in the default Markdown viewer.

.DESCRIPTION
    Finds the most recently written .md report in
    apps/browser-extension/test-results/live/ and opens it with Invoke-Item
    (respects the OS default app for .md files). Also prints the report
    contents to the console.

    If no reports exist, prints guidance on how to generate one and exits
    cleanly (exit 0; "no reports" is not an error).

.PARAMETER Help
    Show usage information and exit.

.PARAMETER PrintOnly
    Print the report to the console without opening the default viewer.
    Used by: pnpm -w run smoke:chatgpt:report

.PARAMETER ReportDir
    Override the directory to search. Defaults to
    apps/browser-extension/test-results/live/ relative to the repo root.

.EXAMPLE
    # Show usage
    .\scripts\open-latest-live-chatgpt-report.ps1 -Help
    pnpm -w run smoke:chatgpt:report -- -Help

.EXAMPLE
    # Print the latest report to the console (no viewer)
    .\scripts\open-latest-live-chatgpt-report.ps1 -PrintOnly
    pnpm -w run smoke:chatgpt:report

.EXAMPLE
    # Open the latest report in the default viewer
    .\scripts\open-latest-live-chatgpt-report.ps1
    pnpm -w run smoke:chatgpt:report:open

.NOTES
    Run: pnpm -w run smoke:chatgpt:live
    Reports are written to apps/browser-extension/test-results/live/
    That directory is git-ignored; reports stay local and are never committed.
    PRIVACY: This script reads only the generated report file, not any
    ChatGPT page content.
#>

[CmdletBinding()]
param(
    [switch]$Help,
    [switch]$PrintOnly,
    [string]$ReportDir = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

function Write-Ok([string]$msg)   { Write-Host ("[OK]  " + $msg) -ForegroundColor Green }
function Write-Info([string]$msg) { Write-Host ("[--]  " + $msg) -ForegroundColor Cyan }
function Write-Err([string]$msg)  { Write-Host ("[ERR] " + $msg) -ForegroundColor Red }

# ---------------------------------------------------------------------------
# Help mode
# ---------------------------------------------------------------------------

if ($Help) {
    Write-Host ""
    Write-Host "SYNOPSIS" -ForegroundColor Cyan
    Write-Host "  Opens (or prints) the latest live ChatGPT smoke report."
    Write-Host ""
    Write-Host "USAGE"
    Write-Host "  .\scripts\open-latest-live-chatgpt-report.ps1 [-PrintOnly] [-ReportDir <path>]"
    Write-Host "  pnpm -w run smoke:chatgpt:report              # print to console"
    Write-Host "  pnpm -w run smoke:chatgpt:report:open         # print + open in default viewer"
    Write-Host "  pnpm -w run smoke:chatgpt:report -- -Help     # show this help"
    Write-Host ""
    Write-Host "OPTIONS"
    Write-Host "  -Help        Show this help and exit."
    Write-Host "  -PrintOnly   Print report to console; do not open the default viewer."
    Write-Host "  -ReportDir   Override the report directory (absolute path)."
    Write-Host ""
    Write-Host "NOTES"
    Write-Host "  Reports are generated by: pnpm -w run smoke:chatgpt:live"
    Write-Host "  Report directory: apps/browser-extension/test-results/live/"
    Write-Host "  (git-ignored; reports stay local, never committed)"
    Write-Host ""
    exit 0
}

# ---------------------------------------------------------------------------
# Locate report directory
# ---------------------------------------------------------------------------

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$RepoRoot  = Split-Path -Parent $ScriptDir

if ($ReportDir -eq "") {
    $ReportDir = Join-Path $RepoRoot "apps/browser-extension/test-results/live"
}

if (-not (Test-Path $ReportDir)) {
    Write-Host ""
    Write-Host "[--] No live ChatGPT smoke reports were found." -ForegroundColor Cyan
    Write-Host "[--] Expected directory does not exist yet:" -ForegroundColor Cyan
    Write-Host ("       " + $ReportDir) -ForegroundColor DarkGray
    Write-Host "[--] To generate a report, run:" -ForegroundColor Cyan
    Write-Host "       pnpm -w run smoke:chatgpt:live" -ForegroundColor Yellow
    Write-Host "[--] Reports are git-ignored and stay local." -ForegroundColor Cyan
    Write-Host ""
    exit 0
}

# ---------------------------------------------------------------------------
# Find the latest report
# ---------------------------------------------------------------------------

$reports = Get-ChildItem -Path $ReportDir -Filter "*.md" -ErrorAction SilentlyContinue |
           Sort-Object LastWriteTime -Descending

if ($reports.Count -eq 0) {
    Write-Host ""
    Write-Host "[--] No live ChatGPT smoke reports were found." -ForegroundColor Cyan
    Write-Host "[--] The directory exists but contains no .md report files:" -ForegroundColor Cyan
    Write-Host ("       " + $ReportDir) -ForegroundColor DarkGray
    Write-Host "[--] To generate a report, run:" -ForegroundColor Cyan
    Write-Host "       pnpm -w run smoke:chatgpt:live" -ForegroundColor Yellow
    Write-Host "[--] Reports are git-ignored and stay local." -ForegroundColor Cyan
    Write-Host ""
    exit 0
}

$latest = $reports[0]

Write-Ok ("Latest report: " + $latest.FullName)
Write-Ok ("Written:       " + $latest.LastWriteTime.ToString("yyyy-MM-dd HH:mm:ss"))

if ($reports.Count -gt 1) {
    Write-Info (("{0} older report(s) also available in: {1}" -f ($reports.Count - 1), $ReportDir))
}

# ---------------------------------------------------------------------------
# Print report contents
# ---------------------------------------------------------------------------

Write-Host ""
Write-Host "---"
Write-Host (Get-Content -Path $latest.FullName -Raw)
Write-Host "---"
Write-Host ""

# ---------------------------------------------------------------------------
# Open in default viewer
# ---------------------------------------------------------------------------

if (-not $PrintOnly) {
    try {
        Invoke-Item $latest.FullName
        Write-Ok "Opened in default viewer."
    } catch {
        Write-Err ("Could not open default viewer: " + $_)
        Write-Info ("View the file manually at: " + $latest.FullName)
        exit 1
    }
}
